DROP TABLE IF EXISTS users, items;

CREATE TABLE users (
  user_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(127) NOT NULL,
  email varchar(127) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (user_id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE items (
  item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(127) NOT NULL,
  description varchar(1020) NOT NULL,
  available boolean NOT NULL,
  owner_id integer NOT NULL,
  CONSTRAINT fk_item_owner FOREIGN KEY (owner_id) REFERENCES users (user_id) ON DELETE CASCADE,
  CONSTRAINT pk_item PRIMARY KEY (item_id)
);